services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tododb
      - JWT_SECRET=secret-key
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
